### PR TITLE
[ttx_diff.py] pass --no-production-names until supported for both .glyphs & DS

### PR DESCRIPTION
**Pull request by anthrotype**
https://github.com/googlefonts/fontc/issues/248#issuecomment-1775429891

JMM

### CODE REVIEW

**Comment by anthrotype** [comment]
there may be a case for keeping --no-production-names flag regardless of whether support for .glyphs input is implemented, since it aids with debugging. For the human reader, it is easier to indentify a diff related to a specific glyph if  the latter is named "acutecomb" instead of "uni0301"...

**Comment by rsheeter** [comment]
As a human reader I would very much prefer to see acutecomb in the diff :)

**Review by rsheeter — APPROVED** [review]
LGTM

**Comment by anthrotype** [comment]
> As a human reader I would very much prefer to see acutecomb in the diff :)

in that case I shall remove the TODO and explain why we prefer to always pass --no-production-names in ttx_diff.py

**Review by rsheeter — APPROVED** [review]
LGTM

**Pull request merged**
