### PR TITLE
Add a graph of dependencies to the README

### PR DESCRIPTION
**Pull request by rictic**
Preview: https://github.com/googlefonts/fontc/tree/readme-depmap?tab=readme-ov-file#dependency-map

Fixes https://github.com/googlefonts/fontc/issues/607

### CODE REVIEW

**Comment by rsheeter** [comment]
It's a wee bit busy right now, so much so I had a bit of a hard time extracting information from it. I wonder if we could prune it down to the most important ones? For example, fauntlet, otexplorer, fea-lsp, font-codegen, freetype-rs, norad, and kurbo all seem like things that maybe could be removed. I think our skrifa dependency might be only for tests so maybe that could drop too.

**Comment by rsheeter** [comment]
For example, while arguably missing key data I find this version, perhaps accompanied by a note that fontc relies on read/write-fonts and kurbo more comprehensible:

```mermaid
%% This is a map of non-dev font-related dependencies.
%% See https://mermaid.live/edit for a lightweight editing environment for
%% mermaid diagrams.
graph TD
    %% First we define the nodes and give them short descriptions.
    %% We group them into subgraphs by repo so that the visual layout
    %% maps to the source layout, as this is intended for contributors.

    %% https://github.com/googlefonts/fontc
    subgraph fontc-repo[fontc repo]
        fontc{{fontc\nCLI font compiler}}
        fontra2fontir[fontra2fontir\nconverts .fontra files to our IR]
        glyphs2fontir[glyphs2fontir\nconverts .glyphs files to our IR]
        ufo2fontir[ufo2fontir\nconverts from a \n.designspace to our IR]        
        fontir[fontir\nthe IR for fontc]
        fontbe[fontbe\nthe backend of font compilation\nIR -> binary font]        
        fea-rs[fea-rs\nParses and compiles\nAdobe OpenType feature files]        
        fontdrasil[fontdrasil\nCommon types and functionality\nshared between all layers of fontc]
    end


    %% Now define the edges.
    %% Made by hand on March 20, 2024, probably not completely correct.
    %% Should be easy to automate if we want to, main thing is to
    %% define the crates of interest.
    fontbe --> fontir
    fontbe --> fea-rs
    fontc --> fontbe
    fontc --> fontir
    fontc --> glyphs2fontir
    fontc --> fontra2fontir
    fontc --> ufo2fontir
    fontra2fontir --> fontir
    glyphs2fontir --> fontir
    ufo2fontir --> fontir
```

That might just be me, if you find the current one more helpful feel free to merge.

**Review by rsheeter — APPROVED** [review]
I think less might be more, left a comment. Happy to have this merged either way.

**Comment by rictic** [comment]
Yeah, simplifying it makes it much more legible.

**Pull request merged**
